management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  output:
    ansi:
      enabled: ALWAYS
foo:
  datasource:
#    内存数据源配置
#    url: jdbc:h2:mem:foo
#    username: sa
#    password:
#    MySQL数据源配置
    url: jdbc:mysql://localhost:3306/learn_spring?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: rootroot
bar:
  datasource:
#    内存数据源配置
#    url: jdbc:h2:mem:bar
#    username: sa
#    password:
#    MySQL数据源配置
    url: jdbc:mysql://localhost:3306/learn_spring?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: rootroot