management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 600000
      connection-timeout: 30000
      connection-test-query: select 1
      max-lifetime: 18000000