--CREATE TABLE FOO (ID INT IDENTITY, BAR VARCHAR(64));
drop TABLE if EXISTS  FOO;

CREATE TABLE `FOO`  (
  `id` bigint UNSIGNED NOT NULL  AUTO_INCREMENT,
  `bar` varchar(100) NULL,
	PRIMARY KEY(`id`)
);